events {
    worker_connections 2048;
}

http {
    keepalive_timeout 3600;
    proxy_read_timeout 3600;
    proxy_send_timeout 3600;

    server {
        listen 8080;

        # VPS1 - VLESS
        location /vps1/vless-ws {
            proxy_pass http://79.133.42.185:10001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_buffering off;
            tcp_nodelay on;
        }

        # VPS1 - VMESS
        location /vps1/vmess-ws {
            proxy_pass http://79.133.42.185:10002;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_buffering off;
            tcp_nodelay on;
        }

        # VPS1 - TROJAN
        location /vps1/trojan-ws {
            proxy_pass http://79.133.42.185:10003;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_buffering off;
            tcp_nodelay on;
        }

        # VPS2 - VLESS
        location /vps2/vless-ws {
            proxy_pass http://81.17.99.235:10001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_buffering off;
            tcp_nodelay on;
        }

        # VPS2 - VMESS
        location /vps2/vmess-ws {
            proxy_pass http://81.17.99.235:10002;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_buffering off;
            tcp_nodelay on;
        }

        # VPS2 - TROJAN
        location /vps2/trojan-ws {
            proxy_pass http://81.17.99.235:10003;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_buffering off;
            tcp_nodelay on;
        }

        location / {
            return 200 "Proxy Online";
        }
    }
}
