events { worker_connections 1024; }

http {
    server {
        listen 8080;

        location /moov-run {
            # Redirige vers ton VPS principal
            proxy_pass http://79.133.42.185:10001;
            
            # Paramètres essentiels pour le protocole WebSocket
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            
            # Désactive le cache pour que le flux soit direct
            proxy_buffering off;
            proxy_request_buffering off;
        }
    }
}
